### ISSUE TITLE
The Google Pay button doesn't show up anymore

### ISSUE THREAD

**Issue by layflags** [stripe/checkout-sales-demo#4]
The Google Pay button doesn't show up anymore in mobile Chrome for a few days now in our web app with Stripe Checkout integration. On Desktop Chrome on Mac it shows up most of the time. I tried to reset the Browser settings, but this doesn't help. Was there a change deployed recently that causes this behaviour? 

As a reference just open the following link and hit the "Donate now" button: https://www.thanku.social/en/app/donate?currency=EUR&donateeGroup=CleanOcean&price=1

_Originally posted by @layflags in https://github.com/stripe/stripe-payments-demo/issues/9#issuecomment-663985749_

**Comment by layflags** [comment]
Same behaviour after clicking on Preview Checkout button here: https://stripe.com/docs/payments/checkout

**Comment by hofman-stripe** [comment]
The Google Pay button on Stripe Checkout only shows if the Google Pay SDK is able to check the logged in account has an enrolled card. A couple things may prevent this from happening:
- You are not logged into your Google account on which Google Pay is configured
- 3rd party cookies are blocked

You haven't described in which exact environment the Google Pay button is not showing up for you? I've just verified it is showing up on Chrome Android while logged into my Google account.

Chrome on iOS doesn't use the Blink engine and is really a WKWebView due to Apple's rules. Apparently Apple has been breaking 3rd party cookies in WKWebView on and off for iOS 13. I have just verified that on the latest iOS 13.6, third party cookies are blocked in Chrome, regardless of Safari's settings to disable ITP or not. There is unfortunately nothing anyone but Apple, can do about this, including Stripe or Google.

Related bugs on Apple's side:
- https://bugs.webkit.org/show_bug.cgi?id=204109
- https://bugs.webkit.org/show_bug.cgi?id=213510

**Comment by hofman-stripe** [comment]
Apparently the Google Pay SDK started throwing errors on Safari browsers so we disabled it entirely on July 2nd. We may be able to re-enable it on Chrome iOS only, but please realize that it would still not work in most iOS versions due to the 3rd party cookie blocking I mentioned.

**Comment by layflags** [comment]
Thanks for the quick response Mathieu! 3rd party cookies were blocked, that was the problem! Now it's working again in Chrome Mobile on Android. But I'm pretty sure it worked before when 3rd party cookies were blocked.

The Chrome team plans to block 3rd party cookies by default in the near future, like other browser vendors do it already. What's the plan if this happens?

**Comment by hofman-stripe** [comment]
That's a question for Google. We simply use their SDK in this case. I'm assuming they will find a way to make Chrome and Google Pay SDK work together.

There is also a lot of work currently going on at the W3C on standardizing payment methods in a privacy preserving way.

**Comment by hofman-stripe** [comment]
We've re-enabled Google Pay on Chrome iOS. It will only work when iOS doesn't block 3rd party cookies in iFrames in WKWebView.

**Comment by storyguy88** [comment]
> We've re-enabled Google Pay on Chrome iOS. It will only work when iOS doesn't block 3rd party cookies in iFrames in WKWebView.

@hofman-stripe Is this only on Checkout? Is it ever possible to show the G Pay button (not the Pay Now button) with Elements?

**Comment by hofman-stripe** [comment]
> Is it ever possible to show the G Pay button (not the Pay Now button) with Elements?

Unfortunately Elements is only a wrapper around the browser's PaymentRequest API, which doesn't allow us to differentiate between the payment method that is configured in the browser (Google Pay or saved card)

**Comment by musfiqurcse** [comment]
@hofman-stripe > I know but there is some other company they are using Google PAY API . I read the case study of boxed.com
![image](https://user-images.githubusercontent.com/7546608/99384571-e88f9f80-28cf-11eb-8505-1ccb41b8509f.png)
Though most of the customer rely on apple pay / googe pay, hence customer is getting confused with **Pay Now** button in Chrome instead of Google Pay/ G Pay button.

**Comment by eobrien-stripe** [comment]
There is a demo built by Thor of how to do the above here: https://glitch.com/~stripe-google-pay
